### ISSUE TITLE
Defend button on Destination screen should flash just like "Start Round"

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#109]
I put the code in to do this, or so I thought, but the code just pushes the text down and doesn't flash.
1. start app
2. start new game

notice the defend button is not flashing

  private void desintation_IsVisibleChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            VisualStateManager.GoToState(desintation.btnGo, "Encouraged", true);
        }

**Comment by patrickdenglerhobbisoft** [comment]
Chris, can you look?

**Comment by patrickdenglerhobbisoft** [comment]
All default buttons should have this; I coded them in as you see above, but they don't work ?

**Comment by christopherdude** [comment]
Yes, standby

**Comment by christopherdude** [comment]
Ok, this works now, but there's a caveat... If a user MOUSES-OVER an encouraged button, it will not continue to be encouraged.  Because it returns to it's "Normal" state... so....... if this is a high desire I can put it in, but there's going to have to be a separate method to check that and move it back.  It'll be weird, but can be done.

**Comment by patrickdenglerhobbisoft** [comment]
let's punt this for now; your fix is good and if someone complains we will resurrect.
