### ISSUE TITLE
Finish round control UI 

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#25]
1. search on:  // TODO : Round Control 
2. comment out the return right below this comment.
3. start the game (turn off start screen and dialogs if helpful)
4. click "begin communications"
5. make that screen look reasonable (it's hideous)  

I'll add more images later. for now use what's there

**Comment by christopherdude** [comment]
![roundcontrol2](https://cloud.githubusercontent.com/assets/9539359/11998144/837018c8-aa4e-11e5-838e-7cb8ee3c1293.png)

I'm thinking something like this which is consistent with the newly suggested MSGBOX (sent in email on 12/24).  It is also consistent with the new panel I did earlier.  Let me know.... I hate to put these things in because sometimes you don't like them and then just replace them, so tell me if this is ok.

I'm trying to make it look rustic, tower-ish, and a little like a computer screen notifying them of incoming stuff.

**Comment by patrickdenglerhobbisoft** [comment]
I simplified the new roundcontrol to look like the tutorial and removed the monster listing to make it even simplified even more.
