### ISSUE TITLE
specular texture is not being included in any of the models ( in drmat/drmdl)

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#34]
Each tower model has a specular.tga, but it doesn't seem to be included in the final rendering?

**Comment by helmut-g** [comment]
I think the problem is that in the FBX the specular texture is used in the "Specular Level" slot of the 3ds max material:
![image](https://cloud.githubusercontent.com/assets/3626369/12003806/fd673eb4-ab2e-11e5-9d27-f8dcfcfee61d.png)

Open Asset Importer only imports specular textures that are assigned to the "Specular Color" slot.

We can change the material of the models in 3DS max or we can manually set the **SpecularTexture** in the DRMAT files by adding the texture to the "Material" pass. For example for the water tower:

``` xml
  ...
  <Pass Name="Material" Effect="DigitalRune/Materials/Material" Profile="HiDef">
    <Parameter Name="DiffuseColor" Value="0.5882353,0.5882353,0.5882353" />
    <Parameter Name="SpecularColor" Value="1.26,1.26,1.26" />
    <Texture Name="DiffuseTexture" Format="Dxt" GenerateMipmaps="True" PremultiplyAlpha="True" File="water_tower.tga" />
    <Texture Name="SpecularTexture" Format="Dxt" GenerateMipmaps="True" PremultiplyAlpha="False" File="water_tower_spec.tga" />
  </Pass>
   ...
```

AFAIK, most specular textures are named like the diffuse texture + "_spec". If have extended the WDModelViewer tool to automatically find specular texture that are named like this.

**Comment by patrickdenglerhobbisoft** [comment]
Had most of these working; then I redid  the models :( if I have time I'll get to the m again.
