### ISSUE TITLE
camera view not set in car yet

### ISSUE THREAD

**Issue by patrickdenglerhobbisoft** [patrickdenglerhobbisoft/WorldDefense#9]
suspect this is somwehre in the car camera view
1. start game
2. start round
3 click on monster to select monster and drive around
4. click "switch view" or press "v"
# OBS

Using awsd does not move the camera around (still drives car)
# EXP

camera is set in back of car

**Comment by helmut-g** [comment]
@patrickdenglerhobbisoft CameraObject.SetCameraViewToCar contained the spectator camera mode from the DR samples but not the other camera mode that positions the camera behind the car. I added the code.

Some possible improvements for the car camera view:
- The current camera has a fixed orientation (always in car direction). We could let the user rotate the camera - as in the DR samples.
- Alternatively, we could let the camera look in car direction but make it more dynamic - similar to the XNA chase camera sample.
- The current camear position behind the car is fixed. The position is hardcoded in CameraObject.SetCameraViewToCar. Since the cars have different size, we could set a specific camera position for each car type - but I am not sure if it worth the effort.

**Comment by patrickdenglerhobbisoft** [comment]
WOrks great
